### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by ghost** [re2005/lifeSlot-client#1]
hello,when I run deploy.sh it show:
/usr/lib/node_modules/parcel-bundler/lib/cli.js:3
let bundle = (() => {
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/parcel-bundler/bin/cli.js:6:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by re2005** [comment]
Hi Pandaju,

This script is used for me only to deploy automatically the bundle to my github account, it won't work for you.
If you want to automate the deploy you have to adjust the git repository url and your local dir.
